# Generated by Django 5.2.4 on 2025-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='Resume URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
