# Generated by Django 5.2.4 on 2025-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfiguration',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF recommended)', null=True, upload_to='resumes/', verbose_name='Resume File'),
        ),
    ]
