# Generated by Django 5.2.4 on 2025-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminexternalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='portfolio_github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio GitHub URL'),
        ),
    ]
