[project]
name = "server"
version = "0.1.0"
description = "Backend API for personal portfolio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "django-cors-headers>=4.7.0",
    "djangorestframework>=3.16.0",
]

[dependency-groups]
dev = [
    "pylint>=3.3.7",
    "pylint-django>=2.6.1",
]
[tool.pylint]
