# Generated by Django 5.2.4 on 2025-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
