# Generated by Django 5.2.4 on 2025-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_certification_credential_id_certification_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='files/certifications/'),
        ),
    ]
