# Generated by Django 5.2.4 on 2025-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_certification_certification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/certifications/'),
        ),
    ]
