# Generated by Django 5.2.4 on 2025-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_certification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this achievement on the portfolio'),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this certification on the portfolio'),
        ),
    ]
