# Generated by Django 5.2.4 on 2025-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this post on the blog'),
        ),
    ]
